Repository Jaserelhabrouk/D_run_and_shoot, pull requests merged in 2020-12, with the labels that each got.

#75 Update, review and cleaning.
  include/map.h
  include/map_textures.h
  include/menu.h
  include/single_player.h
  src/game_over.c
  src/is_player_hit.c
  src/load_map.c
  src/main.c
  src/print_menu.c
  src/single_player.c
  src/win_game.c
  test/game_over_test.c
  test/is_player_hit_test.c
  test/load_map_test.c
  test/print_menu_test.c
  test/win_game_test.c
Labels: enhancement

#76 Ml updates
  src/single_player.c
Labels: enhancement

#78 Add Multiplayer potential to release one.
  data/map_file.txt
  include/map.h
  include/map_textures.h
  include/single_player.h
  src/generate_view.c
  src/is_barrier_hit.c
  src/is_player_hit.c
  src/load_map.c
  src/main.c
  src/single_player.c
  src/take_heart.c
  src/update_arrow.c
Labels: enhancement

#91 Update related files after adding multi_player function.
  Makefile
  data/multi_player_easy.txt
  data/multi_player_hard.txt
  data/multi_player_intermediate.txt
  include/map_textures.h
  include/menu.h
  include/multi_player.h
  src/generate_view_multi.c
  src/main.c
  src/multi_player.c
  src/single_player.c
  src/user_manual.c
Labels: enhancement

#94 Fix multi_player
  src/multi_player.c
Labels: enhancement

#98 Fix shoot and related functions. Update Makefile.
  Makefile
  include/map.h
  src/is_bullet_hit.c
  src/multi_player.c
  src/shoot.c
  test/is_bullet_hit_test.c
  test/load_map_test.c
  test/shoot_test.c
  test/update_bullet_test.c
Labels: bug, enhancement

#99 Modify and complete missed comments. Add Doxyfile.
  Doxyfile
  include/map.h
  include/map_textures.h
  include/menu.h
  include/multi_player.h
  include/single_player.h
  src/credit.c
  src/generate_view.c
  src/generate_view_multi.c
  src/is_barrier_hit.c
  src/is_bullet_hit.c
  src/is_player_hit.c
  src/is_reach_goal.c
  src/multi_player.c
  src/print_menu.c
  src/print_options.c
  src/shoot.c
  src/single_player.c
  src/take_heart.c
  src/update_arrow.c
  src/update_barrier.c
  src/update_bullet.c
  src/update_player_pos.c
  src/user_manual.c
  test/choose_menu_item_test.c
  test/game_over_test.c
  test/generate_view_test.c
  test/is_barrier_hit_test.c
  test/is_bullet_hit_test.c
  test/is_player_hit_test.c
  test/load_map_test.c
  test/shoot_test.c
  test/take_heart_test.c
  test/update_arrow_test.c
  test/update_barrier_test.c
  test/win_game_test.c
Labels: documentation

#100 update deliverable2 documents based on latest changes.
  doc/deliverable2/deliverable2.pdf
  doc/deliverable2/main.tex
  doc/deliverable2/menu.tex
  doc/deliverable2/multiplayer.tex
  doc/deliverable2/options.pdf
  doc/deliverable2/options.tex
  doc/deliverable2/singleplayer.tex
  src/main.c
Labels: documentation

#97 Update README.md
  README.md
Labels: documentation, help wanted

#103 Fixes
  Makefile
  include/map.h
  include/map_textures.h
  include/menu.h
  include/single_player.h
  src/credit.c
  src/game_over.c
  src/generate_view.c
  src/generate_view_multi.c
  src/main.c
  src/multi_player.c
  src/options.c
  src/print_menu.c
  src/print_options.c
  src/single_player.c
  src/user_manual.c
  src/win_game.c
  test/game_over_test.c
  test/generate_view_test.c
  test/is_barrier_hit_test.c
  test/is_bullet_hit_test.c
  test/is_player_hit_test.c
  test/is_reach_goal_test.c
  test/load_map_test.c
  test/print_menu_test.c
  test/print_options_test.c
  test/shoot_test.c
  test/take_heart_test.c
  test/update_arrow_test.c
  test/update_barrier_test.c
  test/update_bullet_test.c
  test/update_player_pos_test.c
  test/win_game_test.c
Labels: enhancement

#101 Add README file.
  README.md
Labels: documentation
